### ISSUE TITLE
'todo edit' prompts error

### ISSUE THREAD

**Issue by rtng** [skoenig/todo#1]
hello :)
'todo edit' prompts me : '/home/pi/bin/todo: Zeile 309: /home/pi/Dokumente/VimWiki/todo.md: Keine Berechtigung' here. OK, that could be done with setting the editor variable to vim and a reboot.
There seems to be a syntax-error in ~/bin/todo:
![todo](https://user-images.githubusercontent.com/67840237/218325785-c17b8998-2207-49e9-9a88-540134a9055e.png)

**Comment by skoenig** [comment]
Hi - good catch! Can you please check out the PR I've created? The group-by-date commands should have been working also with the buggy line you detected, but my change makes it more robust.
Also mentioned that the `EDITOR` environment variable has to be set in the README.

**Comment by rtng** [comment]
Hi, cool I'll try it right away and let you know the result sop.

**Comment by rtng** [comment]
Nice, that's it. No more syntax errors and adding time-defined orders works very smoothly here. (I'm currently looking for suitable software for a screencast :D ). I'm curious how well vimwiki, ranger and your todo list will work together..
